config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import landing_page, GetTest

urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('test/', GetTest.as_view(), name='test')
]

products/urls.py
from django.urls import path
from .views import *

app_name = 'products'
urlpatterns = [
    path('book-list', BookListView.as_view(), name='book-list'),
    path('detail/<int:pk>', BookDetailView.as_view(), name='book-detail'),
    path('delete/<int:pk>', BookDeleteView.as_view(), name='book-delete'),
    path('create', BookCreateView.as_view(), name='create-book'),
    path('add_review/<int:pk>', AddReviewView.as_view(), name='add-review'),
    path('edit_review/<int:pk>', ReviewUpdateView.as_view(), name='edit-review'),
    path('category/', CategoriesListView.as_view(), name='category')
]

products/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from users.models import CustomUser
# Create your models here.


class CategoryBooks(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        db_table = 'category_books'

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        db_table = 'language'

    def __str__(self):
        return self.name


class Books(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    price = models.IntegerField()
    category = models.ForeignKey(CategoryBooks, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='books/', default='default_img/default_book_img.png')
    page = models.IntegerField()
    book_lang = models.ForeignKey(Language, on_delete=models.DO_NOTHING)

    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    class Meta:
        db_table = 'books'

    def __str__(self):
        return self.title


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    class Meta:
        db_table = 'author'

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class BookAuthor(models.Model):
    book = models.ForeignKey(Books, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    class Meta:
        db_table = 'book_author'

    def __str__(self):
        return f'{self.book.title} - {self.author.first_name} {self.author.last_name}'


class Review(models.Model):
    comment = models.CharField(max_length=200)
    star_given = models.IntegerField(
        default=0,
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1)
        ]
     )
    book = models.ForeignKey(Books, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    class Meta:
        db_table ='review'

    def __str__(self):
        return f'{self.star_given} - {self.book.title} - {self.user.username}'

products/forms.py
from django.forms import ModelForm
from django import forms
from products.models import Review


class AddReviewForm(ModelForm):
    star_given = forms.IntegerField(max_value=5, min_value=0)
    class Meta:
        model = Review
        fields = ['comment', 'star_given']


class ReviewUpdateForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['comment', 'star_given']

products/views.py
from django.contrib import messages
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from .forms import AddReviewForm, ReviewUpdateForm
from .models import Books, Review, CategoryBooks
from django.urls import reverse_lazy
# Create your views here.


class BookListView(View):
    def get(self, request):
        book = Books.objects.all().order_by('-id')
        return render(request, 'book/book_list.html', {'book': book})

# class BookListView(ListView):
#     model = Books
#     template_name = 'book/book_list.html'
#     context_object_name = 'book'

class BookDetailView(View):
    def get(self, request, pk):
        book = Books.objects.get(pk=pk)
        reviews = Review.objects.filter(book=pk)
        category_books = Books.objects.filter(category=book.category.pk)
        context = {
            'book': book,
            'reviews': reviews,
            'category_books': category_books
        }
        return render(request, 'book/book_detail.html', context=context)



class BookCreateView(CreateView):
    model = Books
    template_name = 'book/book_create.html'
    fields = '__all__'
    success_url = reverse_lazy('products:book-list')


class BookDeleteView(DeleteView):
    model = Books
    template_name = 'book/book_delete.html'
    success_url = reverse_lazy('products:book-list')


class AddReviewView(LoginRequiredMixin, View):
    def get(self, request, pk):
        books = Books.objects.get(pk=pk)
        add_review_form = AddReviewForm()
        context = {
            'books': books,
            'add_review_form': add_review_form
        }
        return render(request, 'book/add_review.html', context=context)

    def post(self, request, pk):
        books = Books.objects.get(pk=pk)
        add_review_form = AddReviewForm(request.POST)
        if add_review_form.is_valid():
            review = Review.objects.create(
                comment=add_review_form.cleaned_data['comment'],
                book=books,
                user=request.user,
                star_given=add_review_form.cleaned_data['star_given']
            )

            review.save()
            messages.success(request, "Review added successfully.")
            return redirect('products:book-detail', pk=pk)
        else:
            messages.error(request, "Failed to add review. Please check the form.")
            return render(request, 'book/add_review.html', {'books': books, 'add_review_form': add_review_form})


class ReviewUpdateView(View):
    def get(self, request, pk):
        review = Review.objects.get(pk=pk)
        update_review_form = ReviewUpdateForm(instance=review)
        context = {
            'update_review_form': update_review_form
        }
        return render(request, 'book/review_update.html', context=context)

    def post(self, request, pk):
        review = Review.objects.get(pk=pk)
        update_review_form = ReviewUpdateForm(request.POST, instance=review)
        if update_review_form.is_valid():
            # Set the book_id before saving
            update_review = update_review_form.save(commit=False)
            update_review.book_id = review.book_id
            update_review.save()
            return redirect('products:book-detail', pk=review.book_id)
        else:
            return render(request, 'book/review_update.html', {'update_review_form': update_review_form})



class CategoriesListView(View):
    def get(self, request):
        category = CategoryBooks.objects.all()

        return render(request, 'book/products.html', {'categorys': category})

templates/book/add_review.html
{% extends 'base.html'%}

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Add review{% endblock %}</title>
</head>
{% block content %}
<h1>{{ books.title }}</h1>
<form method="post" >
    {% csrf_token %}
    {{ add_review_form.as_p }}
    <input type="submit" value="Add Review">
</form>

{% endblock content%}

templates/book/book_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Book</title>
</head>
<body>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

</body>
</html>

templates/book/book_delete.html
<form method="post">{% csrf_token %}




<p>Are you sure you want to delete "{{ object }}"?</p>




    <input type="submit" value="Confirm">
</form>

<a href="{% url 'products:book-detail' object.pk  %}">No</a>

templates/book/book_detail.html
{% extends 'base.html'%}

<head>
    <meta charset="UTF-8">
    <title>{% block title %} {{ book.title }}{% endblock %}</title>
</head>
{% block content %}
<body>
<h1>Name: {{ book.title }}</h1>
<img src="{{ book.image.url }}" height="200px"> <br><br>
<h4>Description: {{ book.description }}</h4>
<h4>Price: {{ book.price }}</h4>
<h4>Pages: {{ book.page }}</h4>
</body>
<a href="{% url 'products:book-delete' book.pk %}" >Delete</a>
<h2>Reviews</h2>
<a href="{% url 'products:add-review' book.pk %}" >Add Review</a>
{% for review in reviews %}
    <h4>{{ review.user.username }} | {{ review.star_given }}</h4>
     {% if request.user == review.user %}
        <a href="{% url 'products:edit-review' review.pk %}" >Update</a>
        <a href="#" >Delete</a>
    {% endif %}
    <p>{{ review.comment }}</p><hr>

{% endfor %}


<hr><hr>

{% for book in category_books %}
    <div style="display:flex">
            <img src="{{ book.image.url }}" height="80px">

            {{ book.title }}

    </div>
{% endfor %}

{% endblock content%}

templates/book/book_list.html
{% extends "base.html" %}

    <title>{% block title %} Books {% endblock %}</title>

{% block content %}
<body>
<h1>Books Page</h1>
<a href="{% url 'products:create-book'%}">Add Book</a> <br><br><hr>

{% for b in book %}
    <a href="{% url 'products:book-detail' b.pk %}">{{ b.title }}</a> <br><br>
{% endfor %}
</body>
{% endblock content %}

templates/book/products.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Category</title>
</head>
<body>
{% for category in categorys %}

    {{ category.name }}<br>

{% endfor %}
</body>
</html>

templates/book/review_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update Review</title>
</head>
<body>
<h1>Update Review</h1>
<form method="post" >
    {% csrf_token %}
    {{ update_review_form.as_p }}
    <input type="submit" value="Update Review">
</form>
</body>
</html>